package pg.model;

// Generated Feb 7, 2017 12:18:28 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="menu")
public class Menu implements java.io.Serializable {

	private Integer id;
	private String name;
	private String sub;
	private String links;


	public Menu(int id,String name,String sub, String links) {
		this.id = id;
		this.name = name;
		this.sub = sub;
		this.links = links;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "sub", nullable = false, length = 20)
	public String getSub() {
		return this.sub;
	}

	public void setSub(String sub) {
		this.sub = sub;
	}

	@Column(name = "links", nullable = false, length = 50)
	public String getLinks() {
		return this.links;
	}

	public void setLinks(String links) {
		this.links = links;
	}

}
