package pg.model;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAccess generated by hbm2java
 */
@Entity
@Table(name = "useraccess")
public class UserAccess implements java.io.Serializable {

	private Integer id;
	private int ware;
	private int head;
	private int user;
	private int sub;
	private int status;

	public UserAccess() {
	}

	public UserAccess(int ware, int head, int user, int sub, int status) {
		this.ware = ware;
		this.head = head;
		this.user = user;
		this.sub = sub;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ware", nullable = false)
	public int getWare() {
		return this.ware;
	}

	public void setWare(int ware) {
		this.ware = ware;
	}

	@Column(name = "head", nullable = false)
	public int getHead() {
		return this.head;
	}

	public void setHead(int head) {
		this.head = head;
	}

	@Column(name = "user", nullable = false)
	public int getUser() {
		return this.user;
	}

	public void setUser(int user) {
		this.user = user;
	}

	@Column(name = "sub", nullable = false)
	public int getSub() {
		return this.sub;
	}

	public void setSub(int sub) {
		this.sub = sub;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
