package pg.share;

public enum StoreTransaction {
	FABRICS_RECEIVE(1),
	FABRICS_QC(2),
	FABRICS_RETURN(3),
	FABRICS_ISSUE(4),
	FABRICS_ISSUE_RETURN(5),
	FABRICS_TRANSFER_IN(6),
	FABRICS_TRANSFER_OUT(7),
	
	ACCESSORIES_RECEIVE(8),
	ACCESSORIES_QC(9),
	ACCESSORIES_RETURN(10),
	ACCESSORIES_ISSUE(11),
	ACCESSORIES_ISSUE_RETURN(12),
	ACCESSORIES_TRANSFER_IN(13),
	ACCESSORIES_TRANSFER_OUT(14),
	GENERAL_RECEIVE(15),
	GENERAL_QC(16),
	GENERAL_RETURN(17),
	GENERAL_ISSUE(18),
	GENERAL_ISSUE_RETURN(19),
	GENERAL_TRANSFER_IN(20),
	GENERAL_TRANSFER_OUT(21);
	
	private int type;
	private StoreTransaction(int type) {
		this.type = type;
	}
	
	public int getType() {
		return type;
	}
}
